Repository Devcourse-BE6-8-2-Team04/Backend, pull requests merged in 2025-07, with the labels that each got.

#7 chore: 스프링부트 프로젝트 생성 및 초기 설정
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/team04/back/BackApplication.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/team04/back/BackApplicationTests.java
Labels: chore

#17 feature: comment 도메인 패키지 및 기본 레이어 생성
  src/main/java/com/team04/back/domain/comment/comment/controller/CommentController.java
  src/main/java/com/team04/back/domain/comment/comment/entity/Comment.java
  src/main/java/com/team04/back/domain/comment/comment/service/CommentService.java
  src/main/java/com/team04/back/domain/comment/repository/CommentRepository.java
Labels: feature

#27 feature: One Call API 3.0 를 사용하는 WebClient
  build.gradle
  src/main/java/com/team04/back/config/WebClientConfig.java
  src/main/java/com/team04/back/infra/weather/WeatherApiClient.java
  src/main/java/com/team04/back/infra/weather/WeatherApiClientImpl.java
  src/main/java/com/team04/back/infra/weather/dto/AlertData.java
  src/main/java/com/team04/back/infra/weather/dto/CloudCover.java
  src/main/java/com/team04/back/infra/weather/dto/CurrentWeather.java
  src/main/java/com/team04/back/infra/weather/dto/DailyData.java
  src/main/java/com/team04/back/infra/weather/dto/DailyFeelsLike.java
  src/main/java/com/team04/back/infra/weather/dto/DailyTemp.java
  src/main/java/com/team04/back/infra/weather/dto/DaySummaryApiResponse.java
  src/main/java/com/team04/back/infra/weather/dto/HourlyData.java
  src/main/java/com/team04/back/infra/weather/dto/HumiditySummary.java
  src/main/java/com/team04/back/infra/weather/dto/MinutelyData.java
  src/main/java/com/team04/back/infra/weather/dto/OneCallApiResponse.java
  src/main/java/com/team04/back/infra/weather/dto/PrecipitationSummary.java
  src/main/java/com/team04/back/infra/weather/dto/PressureSummary.java
  src/main/java/com/team04/back/infra/weather/dto/TemperatureSummary.java
  src/main/java/com/team04/back/infra/weather/dto/TimeMachineApiResponse.java
  src/main/java/com/team04/back/infra/weather/dto/TimeMachineData.java
  src/main/java/com/team04/back/infra/weather/dto/WeatherDescription.java
  src/main/java/com/team04/back/infra/weather/dto/WeatherOverviewApiResponse.java
  src/main/java/com/team04/back/infra/weather/dto/WindMax.java
  src/main/java/com/team04/back/infra/weather/dto/WindSummary.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/team04/back/infra/weather/WeatherApiClientImplE2ETest.java
Labels: feature

#34 feature: Comment 조건 기반 조회 구현
  src/main/java/com/team04/back/BackApplication.java
  src/main/java/com/team04/back/domain/cloth/cloth/entity/ClothInfo.java
  src/main/java/com/team04/back/domain/comment/comment/controller/CommentController.java
  src/main/java/com/team04/back/domain/comment/comment/dto/CommentDto.java
  src/main/java/com/team04/back/domain/comment/comment/entity/Comment.java
  src/main/java/com/team04/back/domain/comment/comment/repository/CommentRepository.java
  src/main/java/com/team04/back/domain/comment/comment/service/CommentService.java
  src/main/java/com/team04/back/domain/comment/repository/CommentRepository.java
  src/main/java/com/team04/back/domain/weather/weather/entity/WeatherInfo.java
  src/main/java/com/team04/back/domain/weather/weather/enums/Weather.java
  src/main/java/com/team04/back/domain/weather/weather/service/WeatherService.java
  src/test/java/com/team04/back/BackApplicationTests.java
  src/test/java/com/team04/back/domain/comment/comment/controller/CommentControllerTest.java
Labels: feature

#37 chore: SpringDocConfig 작성
  build.gradle
  src/main/java/com/team04/back/config/SpringDocConfig.java
  src/main/resources/application.yml
Labels: chore

#39 refactor: Comment 조회 시 파라미터 관련 예외 처리
  src/main/java/com/team04/back/domain/comment/comment/controller/CommentController.java
  src/main/java/com/team04/back/global/exception/ServiceException.java
  src/main/java/com/team04/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/team04/back/global/rsData/RsData.java
  src/test/java/com/team04/back/domain/comment/comment/controller/CommentControllerTest.java
Labels: refactor

#41 feature: 날씨 정보 조회
  src/main/java/com/team04/back/domain/weather/weather/entity/WeatherInfo.java
  src/main/java/com/team04/back/domain/weather/weather/enums/Weather.java
  src/main/java/com/team04/back/domain/weather/weather/repository/WeatherRepository.java
  src/main/java/com/team04/back/domain/weather/weather/service/WeatherService.java
  src/test/java/com/team04/back/domain/weather/weather/service/WeatherServiceTest.java
Labels: feature

#43 feature: Comment 조회에 페이징 기능 추가
  src/main/java/com/team04/back/domain/comment/comment/controller/CommentController.java
  src/main/java/com/team04/back/domain/comment/comment/repository/CommentRepository.java
  src/main/java/com/team04/back/domain/comment/comment/service/CommentService.java
  src/test/java/com/team04/back/domain/comment/comment/controller/CommentControllerTest.java
Labels: feature

#46 feature: Comment 단건 조회
  src/main/java/com/team04/back/domain/comment/comment/controller/CommentController.java
  src/main/java/com/team04/back/domain/comment/comment/service/CommentService.java
  src/test/java/com/team04/back/domain/comment/comment/controller/CommentControllerTest.java
Labels: feature

#53 feature: 날씨 정보 API 구현
  src/main/java/com/team04/back/domain/weather/weather/controller/WeatherController.java
  src/main/java/com/team04/back/domain/weather/weather/dto/WeatherInfoDto.java
  src/main/java/com/team04/back/domain/weather/weather/entity/WeatherInfo.java
  src/main/java/com/team04/back/domain/weather/weather/service/WeatherService.java
  src/main/java/com/team04/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/team04/back/infra/weather/dto/DailyData.java
  src/test/java/com/team04/back/domain/weather/weather/controller/WeatherControllerTest.java
Labels: feature

#59 fix: WeatherAndClothDto 삭제
  src/main/java/com/team04/back/domain/cloth/cloth/dto/WeatherAndClothDto.java
Labels: fix

#62 feature: 도시 검색 기능 및 API 구현
  src/main/java/com/team04/back/domain/weather/geo/controller/GeoController.java
  src/main/java/com/team04/back/domain/weather/geo/dto/GeoLocationDto.java
  src/main/java/com/team04/back/domain/weather/geo/service/GeoService.java
  src/main/java/com/team04/back/infra/weather/dto/GeoDirectResponse.java
  src/test/java/com/team04/back/domain/weather/geo/controller/GeoControllerTest.java
Labels: feature

#71 chore: API KEY 경로 관련 환경 설정 개선
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: chore

#72 feature: Comment 엔티티에 title 필드 추가
  src/main/java/com/team04/back/domain/comment/comment/dto/CommentDto.java
  src/main/java/com/team04/back/domain/comment/comment/entity/Comment.java
  src/main/java/com/team04/back/global/initData/BaseInitData.java
  src/test/java/com/team04/back/domain/comment/comment/controller/CommentControllerTest.java
Labels: feature

#68 feature: WeatherInfoDto에 weatherCode 칼럼 추가
  src/main/java/com/team04/back/domain/weather/weather/dto/WeatherInfoDto.java
Labels: feature

#74 perf: wether enum 범주 지정
  src/main/java/com/team04/back/domain/cloth/cloth/controller/ClothController.java
  src/main/java/com/team04/back/domain/cloth/cloth/dto/CategoryClothDto.java
  src/main/java/com/team04/back/domain/cloth/cloth/dto/WeatherClothResponseDto.java
  src/main/java/com/team04/back/domain/cloth/cloth/service/ClothService.java
  src/main/java/com/team04/back/domain/weather/weather/dto/WeatherInfoDto.java
  src/main/java/com/team04/back/domain/weather/weather/enums/Weather.java
  src/test/java/com/team04/back/domain/cloth/cloth/controller/ClothControllerTest.java
  src/test/java/com/team04/back/domain/cloth/cloth/service/ClothServiceTest.java
Labels: perf, fix

#78 [fix] Cloth 상세페이지 Response 수정
  src/main/java/com/team04/back/domain/cloth/cloth/dto/ExtraClothDto.java
  src/main/java/com/team04/back/domain/cloth/cloth/mapper/ClothMapper.java
  src/main/java/com/team04/back/domain/cloth/cloth/repository/ClothRepository.java
  src/main/java/com/team04/back/domain/cloth/cloth/service/ClothService.java
Labels: fix

#84 refactor: GeoService.getGeoLocations 수정
  src/main/java/com/team04/back/domain/weather/geo/service/GeoService.java
  src/test/java/com/team04/back/domain/weather/geo/controller/GeoControllerTest.java
Labels: refactor
